[package]
name = "initializer"
version = "1.0.0"
edition = "2024"
rust-version = "1.87"

[dependencies]
gtfs-structures = "0.44.0"
neo4rs = "0.8.0"
tokio = { version = "1.47.1", features = ["rt", "rt-multi-thread", "macros"] }
dialoguer = "0.12"
thiserror = "1.0.69"
indicatif = "0.18.0"
