services:
  neo4j:
    image: neo4j
    container_name: neo4j
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=none
      - NEO4J_initial_dbms_default__database=gtfs
      - NEO4J_server_directories_import=/import
    ports:
      - "7474:7474"   # HTTP (Browser UI)
      - "7687:7687"   # Bolt (Driver connections)
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_plugins:/plugins
      - ./../data/wiener_linien_gtfs:/import/gtfs
      - ./../data/city:/import/city

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_plugins:
